services:
  postgres:
    image: ffijuljani1/postgres
    container_name: postgres
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - petclinic-network
    environment:
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
      POSTGRES_DB: petclinic
  petclinicbe:
    image: ffijuljani1/petclinicbe
    container_name: petclinicbe
    ports:
      - "9966:9966"
    depends_on:
      - postgres
    networks:
      - petclinic-network
  petclinicfe:
    image: ffijuljani1/petclinicfe
    container_name: petclinicfe
    ports:
      - "4200:80"
    networks:
      - petclinic-network

networks:
  petclinic-network:
    name: petclinic-network
    driver: bridge
