services:
  postgres:
    image: ffijuljani1/postgres
    container_name: postgres
    volumes:
      - ./usr/src/app
    ports:
      - "5432:5432"
    networks:
      - petclinic-network
  petclinicbe:
    image: ffijuljani1/petclinicbe
    container_name: petclinicbe
    ports:
      - "9966:9966"
    depends_on:
      - postgres
  petclinicfe:
    image: ffijuljani1/petclinicfe
    container_name: petclinicfe
    ports:
      - "4200:80"

networks:
  petclinic-network:
    name: petclinic-network
    driver: bridge
